package com.julienbirabent.fakeproductscatalogue.data.entity.product

import com.google.firebase.firestore.IgnoreExtraProperties
import com.julienbirabent.fakeproductscatalogue.data.entity.FireStoreAutoGeneratedIdModel

@IgnoreExtraProperties
data class Product(
    var title: String,
    var description: String = "",
    var colors: List<Color> = listOf(),
    var dimensions: Dimensions,
    var price: Float,
    var quantity: Int,
    var imageUrl: String? = null,
    var rating: Rating<*>
) : FireStoreAutoGeneratedIdModel()