package com.julienbirabent.fakeproductscatalogue.data.entity.product

import com.google.firebase.firestore.IgnoreExtraProperties
import com.julienbirabent.fakeproductscatalogue.data.entity.FireStoreAutoGeneratedIdModel
import com.julienbirabent.fakeproductscatalogue.data.entity.ImageResource

@IgnoreExtraProperties
data class Product(
    var title: String,
    var description: String = "",
    var colors: List<ColorResource<*>> = listOf(),
    var dimensions: Dimensions,
    var price: Float,
    var quantity: Int,
    var imageResource: ImageResource<*>? = null,
    var rating: Rating<*>? = null
) : FireStoreAutoGeneratedIdModel()